### ISSUE TITLE
Compass3D Support

### ISSUE THREAD

**Issue by AdamRaichu** [maxoduke/Portal-Linking-Compass#4]
Hey, I just wanted to let you know that I added support for this mod to my mod [Compass3D](https://modrinth.com/mod/compass3d). Compass3D is a client-side mod that adds an overlay arrow to compasses to indicate the y-direction of the target, to make it easier to find the target. Happy modding! :D

**Comment by maxoduke** [comment]
Thanks for letting me know and happy modding to you too!
